fixed crazy indenting

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -12,32 +12,32 @@ printf "[ %s: Running backup script %s ]\n" "$(date)" "${0}"
 
 OPTIND=1
 while getopts "c:b:f:g:G:p:" opt; do
-  case "${opt}" in
-    c)  config_file="${OPTARG}"
-        printf "   config_file: %s\n" "${config_file}"
-        ;;
-    b)  backup_logfile="${OPTARG}"
-        printf "backup_logfile: %s\n" "${backup_logfile}"
-        ;;
-    f)  forget_logfile="${OPTARG}"
-        printf "forget_logfile: %s\n" "${forget_logfile}"
-        ;;
-    g)  gen_logfile="${OPTARG}"
-        printf "   gen_logfile: %s\n" "${gen_logfile}"
-        ;;
-    G)  gen_output="${OPTARG}"
-        printf "    gen_output: %s\n" "${gen_output}"
-        ;;
-    p)  profile_file="${OPTARG}"
-        printf "  profile_file: %s\n" "${profile_file}"
-        ;;
-    :)  printf "Option -%s requires an argument.\n" "${OPTARG}" >&2
-        exit 1
-        ;;
-    \?) printf "Invalid option: -%s\n" "${OPTARG}" >&2
-        exit 1
-        ;;
-  esac
+    case "${opt}" in
+        c)  config_file="${OPTARG}"
+            printf "   config_file: %s\n" "${config_file}"
+            ;;
+        b)  backup_logfile="${OPTARG}"
+            printf "backup_logfile: %s\n" "${backup_logfile}"
+            ;;
+        f)  forget_logfile="${OPTARG}"
+            printf "forget_logfile: %s\n" "${forget_logfile}"
+            ;;
+        g)  gen_logfile="${OPTARG}"
+            printf "   gen_logfile: %s\n" "${gen_logfile}"
+            ;;
+        G)  gen_output="${OPTARG}"
+            printf "    gen_output: %s\n" "${gen_output}"
+            ;;
+        p)  profile_file="${OPTARG}"
+            printf "  profile_file: %s\n" "${profile_file}"
+            ;;
+        :)  printf "Option -%s requires an argument.\n" "${OPTARG}" >&2
+            exit 1
+            ;;
+        \?) printf "Invalid option: -%s\n" "${OPTARG}" >&2
+            exit 1
+            ;;
+    esac
 done
 shift "$((OPTIND-1))"
 
diff --git a/bash_header b/bash_header
--- a/bash_header
+++ b/bash_header
@@ -6,35 +6,36 @@ set -e
 _showed_traceback=f
 
 _exit_trap () {
-  local _ec="$?"
-  if [[ $_ec != 0 && "${_showed_traceback}" != t ]]; then
-    traceback 1
-  fi
+    local _ec="$?"
+    if [[ $_ec != 0 && "${_showed_traceback}" != t ]]; then
+        traceback 1
+    fi
 }
 
 _err_trap() {
-  local _ec="$?"
-  local _cmd="${BASH_COMMAND:-unknown}"
-  traceback 1
-  _showed_traceback=t
-  printf "The command %s exited with exit code %s.\n" "${_cmd}" "${_ec}" 1>&2
+    local _ec="$?"
+    local _cmd="${BASH_COMMAND:-unknown}"
+    traceback 1
+    _showed_traceback=t
+    printf "The command %s exited with exit code %s.\n" \
+        "${_cmd}" "${_ec}" 1>&2
 }
 
 traceback() {
-  # Hide the traceback() call.
-  local -i start=$(( ${1:-0} + 1 ))
-  local -i end=${#BASH_SOURCE[@]}
-  local -i i=0
-  local -i j=0
+    # Hide the traceback() call.
+    local -i start=$(( ${1:-0} + 1 ))
+    local -i end=${#BASH_SOURCE[@]}
+    local -i i=0
+    local -i j=0
 
-  printf "Traceback (last called is first):\n" 1>&2
-  for ((i=start; i < end; i++)); do
-    j=$(( i - 1 ))
-    local function="${FUNCNAME[$i]}"
-    local file="${BASH_SOURCE[$i]}"
-    local line="${BASH_LINENO[$j]}"
-    printf "     %s() in %s:%s\n" "${function}" "${file}" "${line}" 1>&2
-  done
+    printf "Traceback (last called is first):\n" 1>&2
+    for ((i=start; i < end; i++)); do
+        j=$(( i - 1 ))
+        local function="${FUNCNAME[$i]}"
+        local file="${BASH_SOURCE[$i]}"
+        local line="${BASH_LINENO[$j]}"
+        printf "     %s() in %s:%s\n" "${function}" "${file}" "${line}" 1>&2
+    done
 }
 
 # traps
@@ -42,23 +43,15 @@ trap _err_trap SIGHUP SIGINT SIGTERM
 trap _exit_trap EXIT
 trap _err_trap ERR
 
-# how many CPUs?
-if [[ "${SLURM_JOB_CPUS_PER_NODE}" ]]; then
-  max_cpus="${SLURM_JOB_CPUS_PER_NODE}"
-else
-  max_cpus=1
-fi
-ram_limit=$((max_cpus*3000000000))
-
 # handle waiting
 FAIL=0
 fail_wait() {
 for job in $(jobs -p); do
-  wait "${job}" || let "FAIL+=1"
+    wait "${job}" || let "FAIL+=1"
 done
 if [[ ! "${FAIL}" == 0 ]]; then
-  printf "[ %s: Detected fail in background job ]\n" "$(date)"
-  exit 1
+    printf "[ %s: Detected fail in background job ]\n" "$(date)"
+    exit 1
 fi
 }
 
diff --git a/wrapper b/wrapper
--- a/wrapper
+++ b/wrapper
@@ -1,29 +1,34 @@
 #!/bin/bash
 
+# setup
 script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 backup_script="${script_dir}/backup"
 mail_user="$(id -u -n)"
-
 printf "   script_dir: %s\n" "${script_dir}"
 printf "backup_script: %s\n" "${backup_script}"
 
+# declare variables
+config_file=""
+log_dir=""
+
+# setup traceback
 source "${script_dir}/bash_header"
 
 OPTIND=1
 while getopts "c:l:" opt; do
   case "${opt}" in
-    c)  config_file="${OPTARG}"
-        printf " config_file: %s\n" "${config_file}"
-        ;;
-    l)  log_dir="${OPTARG}"
-        printf "     log_dir: %s\n" "${log_dir}"
-        ;;
-    :)  printf "Option -%s requires an argument.\n" "${OPTARG}" >&2
-        exit 1
-        ;;
-    \?) printf "Invalid option: -%s\n" "${OPTARG}" >&2
-        exit 1
-        ;;
+	c)  config_file="${OPTARG}"
+		printf "  config_file: %s\n" "${config_file}"
+		;;
+	l)  log_dir="${OPTARG}"
+		printf "      log_dir: %s\n" "${log_dir}"
+		;;
+	:)  printf "Option -%s requires an argument.\n" "${OPTARG}" >&2
+		exit 1
+		;;
+	\?) printf "Invalid option: -%s\n" "${OPTARG}" >&2
+		exit 1
+		;;
   esac
 done
 shift "$((OPTIND-1))"
@@ -34,16 +39,16 @@ shift "$((OPTIND-1))"
 
 # check variables
 if [[ ! "${log_dir-}" ]]; then
-  log_dir="/var/log/obnam"
-  printf "    log_dir: %s\n" "${log_dir}"
+    log_dir="/var/log/obnam"
+    printf "    log_dir: %s\n" "${log_dir}"
 fi
 if [[ ! "${config_file-}" ]]; then
-  printf "ERROR: specify config_file with -c\n" 1>&2
-  exit 1
+    printf "ERROR: specify config_file with -c\n" 1>&2
+    exit 1
 fi
 if [[ ! -e "${config_file}" ]]; then
-  printf "ERROR: config_file \"%s\" not found\n" "${config_file}" 1>&2
-  exit 1
+    printf "ERROR: config_file \"%s\" not found\n" "${config_file}" 1>&2
+    exit 1
 fi
 
 # set file variables
@@ -57,47 +62,45 @@ profile_file="${log_dir}/obnam.prof"
 # backup and email job
 run_backup() {
   
-  THEN="$(date)"
+    THEN="$(date)"
 
-  # run the backup  
-  srun --job-name=backup --cpus-per-task=1 --output="${script_output}" \
+    # run the backup  
+    srun --job-name=backup --cpus-per-task=1 --output="${script_output}" \
     --nice=1 "${backup_script}" \
     -c "${config_file}" -b "${backup_logfile}" -f "${forget_logfile}" \
     -g "${gen_logfile}" -G "${gen_output}" -p "${profile_file}"
 
-  # mail the output
-  # email notification (move to wrapper)
-  cat <<- _EOF_ | mail -s "[Tom@SLURM] Backup script finished at $(date)" \
-      --attach="${backup_logfile}" --attach="${forget_logfile}" \
-      --attach="${gen_logfile}" ${mail_user}
+    # mail the output
+    # email notification (move to wrapper)
+    cat <<- _EOF_ | mail -s "[Tom@SLURM] Backup script finished at $(date)" \
+        --attach="${backup_logfile}" --attach="${forget_logfile}" \
+        --attach="${gen_logfile}" ${mail_user}
+			Backups started at ${THEN} finished. Logs are attached.
 
-      Backups started at ${THEN} finished. Logs are attached.
+			Backup generations:
 
-      Backup generations:
+			$(cat "${gen_output}")
 
-      $(cat "${gen_output}")
+			Job output:
 
-      Job output:
-
-      $(cat "${script_output}")
-
+			$(cat "${script_output}")
 _EOF_
   
-  # tidy up
-  rm "${backup_logfile}" "${forget_logfile}" "${gen_logfile}" \
-    "${gen_output}" "${script_output}"
-} 
+    # tidy up
+    rm "${backup_logfile}" "${forget_logfile}" "${gen_logfile}" \
+        "${gen_output}" "${script_output}"
+    } 
 
 # check for running backup
-JOBID="$(squeue -n backup -o %A | sed -n 2p)"
+jobid="$(squeue -n backup -o %A | sed -n 2p)"
 
 # exit or run backup
-if [[ "${JOBID}" ]]; then
-  echo "" | mail -s \
-    "[Tom@SLURM] WARNING backup script still in squeue after two hours" \
-    "${mail_user}"
+if [[ "${jobid}" ]]; then
+    echo "" | mail -s \
+        "[Tom@SLURM] WARNING backup script still in squeue after two hours" \
+        "${mail_user}"
 else
-  run_backup
+    run_backup
 fi
 
 exit 0
